### ISSUE TITLE
Persistent snapshots

### ISSUE THREAD

**Issue by ashvardanian** [unum-cloud/ukv#161]

**Comment by VioletaStepanyan** [comment]
8b37373c39348c63c4b63aab0547ac4983f884f8
c8b68f1a8e066d0f22fdc41f471a42be05ce0473
ad43f16466a5b07a139a1d39566ebdd6df5f8532
f553173fab3153169aff2517c699fc8e3b1c3654
f553173fab3153169aff2517c699fc8e3b1c3654
66a95363ed20a5ee955858b42960280f4da13ef0
