### ISSUE TITLE
Temporary collection handles lifetime in Python

### ISSUE THREAD

**Issue by ashvardanian** [unum-cloud/ukv#236]
At this point, we need to preserve the collection handle for as long as the data extracted from it will be needed, meaning this fails with a `SEGFAULT`:

```python
results = db.main[[1, 2, 3]]
results[0]
```

While this works:

```python
main = db.main
results = main[[1, 2, 3]]
results[0]
```

This makes usage unintuitive and very non-Pythonic. To mitigate it, the underlying `ukv_arena_t` instances may be wrapped into `std::shared_ptr`-like abstractions at the PyBind11 layer.

**Comment by davvard** [comment]
d48cf0f73c811b1bf8554d58884aaceccb4292ac
