### ISSUE TITLE
Generating synthetic tweets for benchmarks

### ISSUE THREAD

**Issue by ashvardanian** [unum-cloud/ukv#249]
### Describe what you are looking for

Now the "benchmarks/twitter.cpp" depends on having a local folder with an extensive collection of `.ndjson` files. This limits the reproducibility of the benchmarks and requires moving massive datasets around. To lower the entry bar, the `.cpp` file must receive a function that will generate random tweets, similar to the existing ones in their size and diversity, but be efficient enough not to introduce any new bottlenecks.

In particular, the diversity of `/id`, `/user/id`, `/retweeted_status/id`, `/retweeted_status/user/id` will significantly affect the properties of the constructed graph. The length of `/text` mostly affects the total length of the resulting values. 

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

Native C interface

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VioletaStepanyan** [comment]
d24828fce004633989f17eba4b0fea0553fb5962

**Comment by VioletaStepanyan** [comment]
4442ec0eba9ac783170e2733f9c54065accfaa62
