### ISSUE TITLE
Bug: corrupted size vs. prev_size in fastbins

### ISSUE THREAD

**Issue by AleksandrKent** [unum-cloud/ukv#264]
### Describe the bug

I followed tutorial script with basic use case of UMem with Python. After python finished message `corrupted size vs. prev_size in fastbins` was shown in console.

### Steps to reproduce

Run the script from console `python main.py`
```python
import ukv.umem as embedded

db = embedded.DataBase()
db.main[42] = 'Hi'
```

### Expected behavior

Script silently finishes. 

### UKV version

v0.4.2559

### Operating System

Ubuntu 22.04.1

### Hardware architecture

x86

### Are you using an embedded version?

- [X] I use the embedded version

### Which interface are you using?

Official Python bindings

### Which engine are you using?

UMem

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
It might be solved with the newer minor release we are preparing today. Will keep you posted.

**Comment by ashvardanian** [comment]
@AleksandrKent, I guess this is not an issue anymore, right? Can we close this?
