### ISSUE TITLE
Feature: Build 'UKV Flight Server' from openssl external project as 'UKV Flight Client'

### ISSUE THREAD

**Issue by DarvinHarutyunyan** [unum-cloud/ukv#284]
### Describe what you are looking for

Build 'UKV Flight Server' from openssl external project as 'UKV Flight Client' and remove the dependencies from the system openssl library.

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
@DarvinHarutyunyan, what's the status of this one?

**Comment by ashvardanian** [comment]
I assume a9ead336deecf94eec4c7cf37ff380ff6d28a316 fixes it.
