### ISSUE TITLE
Bug: Python Wheel Builds

### ISSUE THREAD

**Issue by DarvinHarutyunyan** [unum-cloud/ukv#302]
### Describe the bug

Wheel builds failed

### Steps to reproduce

Build

### Expected behavior

Build

### UKV version

v0.7.x

### Operating System

Any

### Hardware architecture

x86

### Are you using an embedded version?

- [ ] I use the embedded version

### Which interface are you using?

Official Python bindings

### Which engine are you using?

UMem

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
@DarvinHarutyunyan what's the status of this issue?
