### ISSUE TITLE
Bug: Incorrect error output

### ISSUE THREAD

**Issue by gurgenyegoryan** [unum-cloud/ukv#325]
### Describe the bug

When I start umem,leveldb or rocksdb server with a different user (non root), which does not have permission to write in the directory specified in the config file, it does not see exactly what the problem is, it just writes

### Steps to reproduce

./leveldb_server --config leveldb/config.json

terminate called after throwing an instance of 'std::runtime_error'
  what():  Opening LevelDB with options
Aborted (core dumped)

### Expected behavior

./leveldb_server --config leveldb/config.json

PermissionError: [Errno 13] Permission denied: '/path/to/folder'

### UKV version

v0.7.6

### Operating System

Ubuntu 22.04

### Hardware architecture

x86

### Are you using an embedded version?

- [X] I use the embedded version

### Which interface are you using?

Other

### Which engine are you using?

LevelDB

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itroyano** [comment]
Thanks @gurgenyegoryan .
The output turned out correct & this issue can be closed as a bug.

I will open a feature request for verbose output for leveldb and rocksdb.

**Comment by gurgenyegoryan** [comment]
Тhank you too @itroyano
